# SITE CONFIGURATION
title: Yonghoon Park # your site title
author: jim6829 # You :P
description: >- # Meta description of Homepage
  Yonghoon Park's portfolio.
  Coder who can design, designer who can code.
  Interested in HCI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Categories', link: '/categories'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Coder who can design, designer who can code.
  Interested in HCI.

hero_img: hero.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: ypark6829@gmail.com # email for form submission

twitter_username: / # replace with your_twitter_username or comment to remove link from footer
github_username: jim6829 # replace with your_github_username or comment to remove link from footer
instagram_username: / # replace with your_instagram_username or comment to remove link from footer
facebook_username: /

disqus:
  #shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
